var vue = new Vue({
    el:"#app",
    data:{
        users:[
            {id:1, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:2, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:3, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:4, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:5, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:5, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:5, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:5, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:6, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:7, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"},
            {id:8, nickname:"xiaojuzi", headImgUrl: "/images/default.jpg"}
            ]
    },
    methods:{

    },
    filters:{

    },
    mounted:function () {
        var param = getParams();
    }
});

